# =============================================================================
# MARINEFLOW — Pub/Sub Module
# infra/terraform/modules/pubsub/main.tf
# =============================================================================

locals {
  # Centralized definition of all project topics
  topics = {
    "vessel-positions" = {
      description = "Real-time AIS positions for all tracked vessels"
    }
    "vessel-metadata" = {
      description = "Static vessel information: name, type, flag, dimensions"
    }
    "port-events" = {
      description = "Vessel arrival and departure events at ports"
    }
    "maritime-alerts" = {
      description = "Alerts generated by the Anomaly Detector model"
    }
    "dead-letter-queue" = {
      description = "Messages that failed processing — for diagnosis and replay"
    }
  }
}

# -----------------------------------------------------------------------------
# Topics
# -----------------------------------------------------------------------------
resource "google_pubsub_topic" "topics" {
  for_each = local.topics

  name    = each.key
  project = var.project_id
  labels  = merge(var.labels, { topic = each.key })

  message_retention_duration = "${var.message_retention_days * 86400}s"

  message_storage_policy {
    allowed_persistence_regions = ["us-central1"]
  }
}

# -----------------------------------------------------------------------------
# Subscriptions — one per topic for the Spark consumer
# Spark Structured Streaming reads from these subscriptions
# -----------------------------------------------------------------------------
resource "google_pubsub_subscription" "spark_subscriptions" {
  for_each = local.topics

  name    = "${each.key}-spark-sub"
  topic   = google_pubsub_topic.topics[each.key].name
  project = var.project_id
  labels  = merge(var.labels, { consumer = "spark" })

  ack_deadline_seconds = var.ack_deadline_seconds

  # Retain unacknowledged messages for the full retention window
  message_retention_duration = "${var.message_retention_days * 86400}s"
  retain_acked_messages      = false

  # Exponential backoff retry policy
  retry_policy {
    minimum_backoff = "10s"
    maximum_backoff = "600s"
  }

  # Dead letter policy for all topics except the DLQ itself
  dynamic "dead_letter_policy" {
    for_each = each.key != "dead-letter-queue" ? [1] : []
    content {
      dead_letter_topic     = google_pubsub_topic.topics["dead-letter-queue"].id
      max_delivery_attempts = 5
    }
  }

  expiration_policy {
    ttl = ""  # never expires — important for the streaming pipeline
  }
}

# -----------------------------------------------------------------------------
# Additional subscription for the FastAPI layer (consumes alerts in real time)
# -----------------------------------------------------------------------------
resource "google_pubsub_subscription" "api_alerts_subscription" {
  name    = "maritime-alerts-api-sub"
  topic   = google_pubsub_topic.topics["maritime-alerts"].name
  project = var.project_id
  labels  = merge(var.labels, { consumer = "fastapi" })

  ack_deadline_seconds       = 30
  message_retention_duration = "86400s"  # 1 day is enough for the API layer

  retry_policy {
    minimum_backoff = "5s"
    maximum_backoff = "60s"
  }

  expiration_policy {
    ttl = ""
  }
}

# -----------------------------------------------------------------------------
# IAM — Pub/Sub service account needs Storage Object Creator on the GCS bucket
# This is required for Cloud Storage subscriptions to write files.
# -----------------------------------------------------------------------------
# Pub/Sub needs both roles at bucket level — GCP requirement for GCS subscriptions
resource "google_storage_bucket_iam_member" "pubsub_gcs_writer" {
  bucket = var.gcs_bucket
  role   = "roles/storage.objectCreator"
  member = "serviceAccount:${var.pubsub_sa_email}"
}

resource "google_storage_bucket_iam_member" "pubsub_gcs_reader" {
  bucket = var.gcs_bucket
  role   = "roles/storage.legacyBucketReader"
  member = "serviceAccount:${var.pubsub_sa_email}"
}

# -----------------------------------------------------------------------------
# Cloud Storage subscriptions — vessel-positions and vessel-metadata
#
# GCP writes Pub/Sub messages directly to GCS as JSON files.
# Each file contains a batch of messages in the Pub/Sub envelope format:
#   {
#     "subscription": "...",
#     "message": {
#       "data": "<base64 encoded JSON>",
#       "messageId": "...",
#       "publishTime": "...",
#       "attributes": {...}
#     }
#   }
#
# Spark Bronze reads these files with Structured Streaming.
# max_duration=60s means a new file is flushed at most every 60 seconds.
# -----------------------------------------------------------------------------
resource "google_pubsub_subscription" "positions_gcs" {
  name    = "vessel-positions-gcs-sub"
  topic   = google_pubsub_topic.topics["vessel-positions"].name
  project = var.project_id
  labels  = merge(var.labels, { consumer = "gcs", topic = "vessel-positions" })

  cloud_storage_config {
    bucket          = var.gcs_bucket
    filename_prefix = "pubsub-landing/vessel-positions/"
    filename_suffix = ".json"

    max_duration = "60s"
    max_bytes    = 10485760  # 10 MB — flush whichever comes first
  }

  expiration_policy {
    ttl = ""
  }

  depends_on = [
    google_storage_bucket_iam_member.pubsub_gcs_writer,
    google_storage_bucket_iam_member.pubsub_gcs_reader,
  ]
}

resource "google_pubsub_subscription" "metadata_gcs" {
  name    = "vessel-metadata-gcs-sub"
  topic   = google_pubsub_topic.topics["vessel-metadata"].name
  project = var.project_id
  labels  = merge(var.labels, { consumer = "gcs", topic = "vessel-metadata" })

  cloud_storage_config {
    bucket          = var.gcs_bucket
    filename_prefix = "pubsub-landing/vessel-metadata/"
    filename_suffix = ".json"

    max_duration = "60s"
    max_bytes    = 10485760
  }

  expiration_policy {
    ttl = ""
  }

  depends_on = [
    google_storage_bucket_iam_member.pubsub_gcs_writer,
    google_storage_bucket_iam_member.pubsub_gcs_reader,
  ]
}
